server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://tcyaljplekbojz:508dc62b9bd12d1b68014f246337dae895ae100c534b72bb0de45387e87c2f46@ec2-54-152-185-191.compute-1.amazonaws.com:5432/d7uup6gr55cgr
    username: tcyaljplekbojz
    password: 508dc62b9bd12d1b68014f246337dae895ae100c534b72bb0de45387e87c2f46
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander / Backend
  version: 2.0.0
